import { Navbar } from './components/Navbar'
import { Hero } from './components/Hero'
import { About } from './components/About'
import { Skills } from './components/Skills'
import { Services } from './components/Services'
import { Projects } from './components/Projects'
import { Education } from './components/Education'
import { Contact } from './components/Contact'
import { Footer } from './components/Footer'
import './styles.css'
export default function App(){return <><Navbar/><main><Hero/><About/><Skills/><Services/><Projects/><Education/><Contact/></main><Footer/></>}
